In [9]:
import numpy as np

arr = np.arange(1,21)
print("Array:")
print(arr)

print("\nShape of array:" , np.shape(arr))
print("\nShape of array:" , arr.shape)
print("\nMaximum value", arr.max())
print("\nMinimum value" , arr.min())
print("\nmean of the array" , arr.mean())
print("\n Standard deviation of the array" , arr.std())

matrix = arr.reshape(4,5)
print(matrix)
print("\nSecond row:")
print(matrix[1])

print("\nThird column:")
print(matrix[:,2])

      

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Shape of array: (20,)

Shape of array: (20,)

Maximum value 20

Minimum value 1

mean of the array 10.5

 Standard deviation of the array 5.766281297335398
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Second row:
[ 6  7  8  9 10]

Third column:
[ 3  8 13 18]


In [12]:
import numpy as np
A = np.array([10 , 20 , 30 , 40 , 50])
B = np.array([5 , 10 , 15 , 20 , 25])
print("Addition:" , A + B)
print("Subtraction:" , A - B)
print("Multiplication:" , A * B)
print("Division:" , A / B)
print("Sum of of array A:" , A.sum())




Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]
Sum of of array A: 150


In [24]:
import pandas as pd
data = {
    "Roll No": [ 101 , 102 , 103 , 104 , 105],
    "Name" : ["Ravi" , "Priya" , "Kiran" , " Anu" , "Sita"],
    "Marks": [85, 92 , 78 , 88 , 98]
}
df = pd.DataFrame(data)
print("Data Frame:" ,df)
print("\nFirst Three Rows:" , df.head(3))
print("\nAverage marks:" , df["Marks"].mean())
print("\nStudent with Heighest Marks:\n" , df.loc[df["Marks"].idxmax()])
print("\nStudent with Lowest Marks:\n" , df.loc[df["Marks"].idxmin()])

def grade(Marks):
    if Marks >=90:
        return"A"
    elif Marks >=80:
        return "B"
    else:
        return "C"

df["Grade"] = df["Marks"].apply(grade)
print("\nDataFrame with Grade:\n" , df)


Data Frame:    Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     98

First Three Rows:    Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

Average marks: 88.2

Student with Heighest Marks:
 Roll No     105
Name       Sita
Marks        98
Name: 4, dtype: object

Student with Lowest Marks:
 Roll No      103
Name       Kiran
Marks         78
Name: 2, dtype: object

DataFrame with Grade:
    Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     98     A


In [28]:
import pandas as pd
data = {
    "Product": ["Laptop" , "Mouse"  ,"keyboard" , "Monitor"],
    "Price" : [50000 , 500 , 1200 , 10000],
    "Quantity": [10 , 50 , 30 , 15]
}
df = pd.DataFrame(data)
df["Total Value"] = df["Price"] * df["Quantity"]
print(df)
print("\nHeighest total value Product :\n" , df.loc[df["Total Value"].idxmax()])
print("\nOverall Inverntory Value:" , df["Total Value"] .sum())

    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  keyboard   1200        30        36000
3   Monitor  10000        15       150000

Heighest total value Product :
 Product        Laptop
Price           50000
Quantity           10
Total Value    500000
Name: 0, dtype: object

Overall Inverntory Value: 711000
